coverage_service: coveralls
xcodeproj: ./Hamcrest.xcodeproj
xcworkspace: ./Hamcrest.xcworkspace
scheme: Hamcrest-macOS
configuration: Debug
source_directory: Hamcrest
output_directory: ./coverage
ignore:
