language: objective-c
osx_image: xcode7.3
sudo: false

before_install:
  - gem install --no-document cocoapods xcpretty

script:
  - set -o pipefail; xcodebuild -workspace *.xcworkspace -scheme "Hamcrest OSX" build test | xcpretty -c
  - set -o pipefail; xcodebuild -workspace *.xcworkspace -scheme "Hamcrest iOS" -sdk iphonesimulator build test | xcpretty -c
  - pod lib lint
